### ISSUE TITLE
See OPNsense Patchlevel on CMD is too nested

### ISSUE THREAD

**Issue by backstube** [opnsense/update#14]
Hey,
in order to see the actual minor release level of an OPNsense box, these steps are currently required:

1. Login via ssh, be welcomed with "Hello, this is OPNsense 17.1"
2. Enter 8 for a shell
3. CTRL-D or 'exit' to leave the shell right away
4. Here we have it: "opnsense.cs: OPNsense **17.1.4** (i386/OpenSSL)"

I feel, this should be printed ealier, like just with the Hello greeting message.

**Comment by fichtner** [comment]
Hmm, you can hit Enter to loop the menu... I remember the banner was moved behind the loop because the locked console would otherwise print a repeated banner like so:

OPNsense VERSION...

login:
password:

OPNsensen VERSION..

MENU

**Comment by backstube** [comment]
> Hmm, you can hit Enter to loop the menu...

Oh yes!  That helps a lot. Thanks. And thank you for the very speedy response, too :-)

**Comment by fichtner** [comment]
Sure thing. :)

I'm not opposed to changing the behaviour. I haven't done so because out of lack of ideas. All hints are welcome.


Cheers,
Franco
