### ISSUE TITLE
running bootstrap script removes pkg itself and results in ssl verification error.

### ISSUE THREAD

**Issue by mtmr** [opnsense/update#25]
Steps for reproducing 
run the bootstrap script in a vanilla freebsd installation and it will fail with an ssl error.
reason:
pkg delete -a should remove all packages except pkg, but it also removes pkg itself, and it basically stops everything else.

Will update with the exact error within few hours.

**Comment by fichtner** [comment]
Did you follow the code example in https://github.com/opnsense/update#opnsense-bootstrap ?

**Comment by mtmr** [comment]
yes. I cannot reproduce it immediately, since this box on aws is the only one I have for now.
I think pkg delete -fa is the command that causes this error.
I had to install pkg by manually compiling and installing, and then used the -b (bare installation option) and then manually did the pkg bootstrap, pkg install opnsense and opnsense-update -bkf

**Comment by mtmr** [comment]
This basically removes pkg, according to the man page 

> -f, --force
                Forces packages to be removed despite leaving unresolved
                dependencies.  In combination with the -a or --all flag,
                causes pkg(8) to be removed as well as all other packages.

and because of this, all the next steps in the script that use the pkg command fail.

**Comment by fichtner** [comment]
Hmmm, should have been an all-in-one run unless something changed with either our mirror or the FreeBSD one that caused an incompatibility.

It's supposed to remove pkg, because we have our own pkg...

**Comment by mtmr** [comment]
I didn't know opnsense had it's own pkg. Should install pkg after installing opnsense and updating? 
If you need any more information tracking the source, please ask. Thanks a lot for the immediate response.

**Comment by fichtner** [comment]
"pkg bootstrap" will work even if pkg is not installed :)

**Comment by fichtner** [comment]
sure, looking forward to the error message. if indeed an error should be trivial to fix.

**Comment by mtmr** [comment]
`root@ip:/usr/home/ec2-user # sh ./opnsense-bootstrap.sh
This utility will attempt to turn this installation into the latest
OPNsense 17.7 release.  All packages will be deleted, the base
system and kernel will be replaced, and if all went well the system
will automatically reboot.

Proceed with this action? [y/N]: y

Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:11:amd64/quarterly, please wait...
Verifying signature with trusted certificate pkg.freebsd.org.2013102301... done
Installing pkg-1.10.1...
package pkg is already installed, forced install
Extracting pkg-1.10.1: 100%
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Updating database digests format: 100%
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed
fetch: https://github.com/opnsense/core/archive/stable/17.7.tar.gz: size of remote file is not known
/tmp/opnsense-bootstrap/4067/core.tar.gz              6263 kB   14 MBps 00m00s
pkg: 26 packages installed
awscli-1.11.123: already unlocked
ca_root_nss-3.32.1: already unlocked
dual-dhclient-1.0: already unlocked
ec2-scripts-1.10: already unlocked
firstboot-freebsd-update-1.2: already unlocked
firstboot-pkgs-1.5: already unlocked
gettext-runtime-0.19.8.1_1: already unlocked
indexinfo-0.2.6: already unlocked
isc-dhcp43-client-4.3.5: already unlocked
libffi-3.2.1_1: already unlocked
pkg-1.10.1: already unlocked
py27-botocore-1.5.86: already unlocked
py27-colorama-0.3.7: already unlocked
py27-dateutil-2.6.1: already unlocked
py27-docutils-0.14: already unlocked
py27-futures-3.1.1: already unlocked
py27-jmespath-0.9.0_1: already unlocked
py27-pyasn1-0.2.2: already unlocked
py27-rsa-3.4.2: already unlocked
py27-s3transfer-0.1.10: already unlocked
py27-setuptools-36.2.2: already unlocked
py27-six-1.11.0: already unlocked
py27-yaml-3.11_2: already unlocked
python27-2.7.14: already unlocked
readline-7.0.3: already unlocked
zsh-5.4.2: already unlocked
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 26 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
	awscli-1.11.123
	ca_root_nss-3.32.1
	dual-dhclient-1.0
	ec2-scripts-1.10
	firstboot-freebsd-update-1.2
	firstboot-pkgs-1.5
	gettext-runtime-0.19.8.1_1
	indexinfo-0.2.6
	isc-dhcp43-client-4.3.5
	libffi-3.2.1_1
	pkg-1.10.1
	py27-botocore-1.5.86
	py27-colorama-0.3.7
	py27-dateutil-2.6.1
	py27-docutils-0.14
	py27-futures-3.1.1
	py27-jmespath-0.9.0_1
	py27-pyasn1-0.2.2
	py27-rsa-3.4.2
	py27-s3transfer-0.1.10
	py27-setuptools-36.2.2
	py27-six-1.11.0
	py27-yaml-3.11_2
	python27-2.7.14
	readline-7.0.3
	zsh-5.4.2

Number of packages to be removed: 26

The operation will free 141 MiB.
[1/26] Deinstalling awscli-1.11.123...
[1/26] Deleting files for awscli-1.11.123: 100%
[2/26] Deinstalling py27-s3transfer-0.1.10...
[2/26] Deleting files for py27-s3transfer-0.1.10: 100%
[3/26] Deinstalling py27-botocore-1.5.86...
[3/26] Deleting files for py27-botocore-1.5.86: 100%
[4/26] Deinstalling py27-dateutil-2.6.1...
[4/26] Deleting files for py27-dateutil-2.6.1: 100%
[5/26] Deinstalling py27-rsa-3.4.2...
[5/26] Deleting files for py27-rsa-3.4.2: 100%
[6/26] Deinstalling py27-colorama-0.3.7...
[6/26] Deleting files for py27-colorama-0.3.7: 100%
[7/26] Deinstalling py27-docutils-0.14...
[7/26] Deleting files for py27-docutils-0.14: 100%
[8/26] Deinstalling py27-futures-3.1.1...
[8/26] Deleting files for py27-futures-3.1.1: 100%
[9/26] Deinstalling py27-jmespath-0.9.0_1...
[9/26] Deleting files for py27-jmespath-0.9.0_1: 100%
[10/26] Deinstalling py27-pyasn1-0.2.2...
[10/26] Deleting files for py27-pyasn1-0.2.2: 100%
[11/26] Deinstalling py27-six-1.11.0...
[11/26] Deleting files for py27-six-1.11.0: 100%
[12/26] Deinstalling py27-yaml-3.11_2...
[12/26] Deleting files for py27-yaml-3.11_2: 100%
[13/26] Deinstalling py27-setuptools-36.2.2...
[13/26] Deleting files for py27-setuptools-36.2.2: 100%
[14/26] Deinstalling python27-2.7.14...
[14/26] Deleting files for python27-2.7.14: 100%
[15/26] Deinstalling dual-dhclient-1.0...
[15/26] Deleting files for dual-dhclient-1.0: 100%
[16/26] Deinstalling gettext-runtime-0.19.8.1_1...
[16/26] Deleting files for gettext-runtime-0.19.8.1_1: 100%
[17/26] Deinstalling libffi-3.2.1_1...
[17/26] Deleting files for libffi-3.2.1_1: 100%
[18/26] Deinstalling readline-7.0.3...
[18/26] Deleting files for readline-7.0.3: 100%
[19/26] Deinstalling ca_root_nss-3.32.1...
[19/26] Deleting files for ca_root_nss-3.32.1: 100%
[20/26] Deinstalling ec2-scripts-1.10...
[20/26] Deleting files for ec2-scripts-1.10: 100%
[21/26] Deinstalling firstboot-freebsd-update-1.2...
[21/26] Deleting files for firstboot-freebsd-update-1.2: 100%
[22/26] Deinstalling firstboot-pkgs-1.5...
[22/26] Deleting files for firstboot-pkgs-1.5: 100%
[23/26] Deinstalling indexinfo-0.2.6...
[23/26] Deleting files for indexinfo-0.2.6: 100%
[24/26] Deinstalling isc-dhcp43-client-4.3.5...
[24/26] Deleting files for isc-dhcp43-client-4.3.5: 100%
[25/26] Deinstalling pkg-1.10.1...
[25/26] Deleting files for pkg-1.10.1: 100%
[26/26] Deinstalling zsh-5.4.2...
[26/26] Deleting files for zsh-5.4.2: 100%
etc/pkg -> /usr/local/etc/pkg
etc/pkg/fingerprints -> /usr/local/etc/pkg/fingerprints
etc/pkg/fingerprints/OPNsense -> /usr/local/etc/pkg/fingerprints/OPNsense
etc/pkg/fingerprints/OPNsense/revoked -> /usr/local/etc/pkg/fingerprints/OPNsense/revoked
etc/pkg/fingerprints/OPNsense/revoked/pkg.opnsense.org.20150402 -> /usr/local/etc/pkg/fingerprints/OPNsense/revoked/pkg.opnsense.org.20150402
etc/pkg/fingerprints/OPNsense/revoked/pkg.opnsense.org.20160104 -> /usr/local/etc/pkg/fingerprints/OPNsense/revoked/pkg.opnsense.org.20160104
etc/pkg/fingerprints/OPNsense/revoked/pkg.opnsense.org.20160630 -> /usr/local/etc/pkg/fingerprints/OPNsense/revoked/pkg.opnsense.org.20160630
etc/pkg/fingerprints/OPNsense/revoked/pkg.opnsense.org.20161210 -> /usr/local/etc/pkg/fingerprints/OPNsense/revoked/pkg.opnsense.org.20161210
etc/pkg/fingerprints/OPNsense/trusted -> /usr/local/etc/pkg/fingerprints/OPNsense/trusted
etc/pkg/fingerprints/OPNsense/trusted/opnsense-update.deciso.com.20160725 -> /usr/local/etc/pkg/fingerprints/OPNsense/trusted/opnsense-update.deciso.com.20160725
etc/pkg/fingerprints/OPNsense/trusted/opnsense-update.deciso.com.20170721 -> /usr/local/etc/pkg/fingerprints/OPNsense/trusted/opnsense-update.deciso.com.20170721
etc/pkg/fingerprints/OPNsense/trusted/pkg.opnsense.org.20170625 -> /usr/local/etc/pkg/fingerprints/OPNsense/trusted/pkg.opnsense.org.20170625
etc/pkg/repos -> /usr/local/etc/pkg/repos
etc/pkg/repos/FreeBSD.conf.shadow -> /usr/local/etc/pkg/repos/FreeBSD.conf.shadow
etc/pkg/repos/origin.conf.shadow.in -> /usr/local/etc/pkg/repos/origin.conf.shadow.in
/usr/local/etc/pkg/repos/FreeBSD.conf.shadow -> /usr/local/etc/pkg/repos/FreeBSD.conf
/usr/local/etc/pkg/repos/origin.conf.shadow.in -> /usr/local/etc/pkg/repos/origin.conf.shadow
/usr/local/etc/pkg/repos/origin.conf.shadow -> /usr/local/etc/pkg/repos/origin.conf
Bootstrapping pkg from pkg+http://pkg.opnsense.org/FreeBSD:11:amd64/17.7/latest, please wait...
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34389693848:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1264:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34389693848:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1264:
Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
34389693848:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/s3_clnt.c:1264:
pkg: Error fetching http://pkg.opnsense.org/FreeBSD:11:amd64/17.7/latest/Latest/pkg.txz: Authentication error
A pre-built version of pkg could not be found for your system.
Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.
root@ip:/usr/home/ec2-user # `

**Comment by mtmr** [comment]
sorry for the delay in providing the logs. I think issue is that since all packages are removed, it also removes the package that provides the ssl certs. pkg bootstrap seems to hit a http endpoint that redirects to https, and ultimately that fails since it cannot verify the ssl cert, since there are no certs at all. Correct me if I am wrong. Thanks. :)

**Comment by fichtner** [comment]
yes, you are right. the problem is the mirror is not supposed to do this, but it was probably changed when we switched servers.

@AdSchellevis can you change our mirror to not bump http to https?

**Comment by AdSchellevis** [comment]
@fichtner should be fixed now. since our new servers, we reflect all to https, disabled it for pkg.opnsense.org

**Comment by fichtner** [comment]
perfect, thanks! @mtmr can you try again?

**Comment by fichtner** [comment]
PS: the update servers have signed sets, https does not add privacy or security in these cases

**Comment by mtmr** [comment]
Thanks @fichtner. Works perfectly now. It's encouraging to have this kind of response when I'm convincing people to move from pfsense to opnsense. :)

**Comment by fichtner** [comment]
@mtmr happy to help, nice catch!
