### ISSUE TITLE
Unable to configure WAN IP when installing in cloudstack

### ISSUE THREAD

**Issue by mtmr** [opnsense/update#26]
Hey,
I was unable to find any documentation on how to add a WAN IP when I am installing opnsense over freebsd using the bootstrap script. Is there anyway to do this? I cannot access the console to configure the IP, and have no way of reaching it through SSH either. 

Thanks

**Comment by fichtner** [comment]
hi @mtmr,

To be honest we know nothing of how cloudstack deployments work in practice and what requirements they have for LAN and WAN. During bootstrap you can prepare an appropriate /conf/config.xml file that will be used after first boot, but what is in that config.xml with accordance to cloudstack is the bigger question to figure out.

A good start is a WAN-only setup with either DHCP or static IP setup to get things started: anti-lockout will unlock the GUI so you can reach an further configure OPNsense from there. Switching on SSH works from there too (if not already done in the initial config.xml).


Cheers,
Franco

**Comment by mtmr** [comment]
Hey Franco, 

Sorry for the delay in reply. I tried setting up a wan only config as you mentioned by removing the lan block altogether, and that didn't work, since opnsense didn't pick up the ip address at all, even though i had enabled dhcp for that interface. What could be the reason for this?
I also tried specifying the ip manually by giving the ip that cloudstack assigns as a static ip, but even then, I was not able to ping/ssh the machine. traceroute shows that the packets are dropped just before the machine, meaning opnsense is not answering for that ip. any thoughts? Your help is much appreciated.

**Comment by fichtner** [comment]
What internal interface names are visible in OPNsense on cloudstack? You may have a mismatch in the names so that fails... You can compare to FreeBSD (e.g. ifconfig) and test which interface is which by testing it for connectivity prior to bootstrap. :)

**Comment by fichtner** [comment]
Then again you already know which, because the bootstrap is working, hehe!

**Comment by mtmr** [comment]
Hey Franco,
I managed to get it working by disabling lan, and assigning wan as a dhcp with the correct interface name. I also got it up on AWS, but do not know what your policy is on publishing ami's. Seems like the only way to get an AMI is to subscribe to Deciso. If you guys are okay, I can make the ami public and share the link here. Thanks for your help :)

**Comment by fichtner** [comment]
@mtmr great to hear, feel free to publish and share :)

**Comment by jschellevis** [comment]
@mtmr I fully agree with Franco, go ahead and share it.
