### ISSUE TITLE
Blank screen on VPS

### ISSUE THREAD

**Issue by hdavy2002** [opnsense/update#27]
I am using Lightsail vps from amazon and after performing this test. it gives me a black screen. Last thing it told me to reboot. I guess it is waiting for me to log in via gui. On a vps, I have no access to gui.

**Comment by fichtner** [comment]
Hi @hdavy2002,

We need more context here... did you use opnsense-bootstrap, if so which version, how did you install FreeBSD, and so on... if you had a console, the console not coming back could be a kernel boot error or an incompatibility in the setup (vga vs. serial).


Cheers,
Franco
