### ISSUE TITLE
Cannot access SSH or HTTPs on both LAN and WAN, despite altering configuration before initial reboot.

### ISSUE THREAD

**Issue by Ramzihakim** [opnsense/update#34]
I've deployed the install/update script on Azure. I saw that the interfaces were configured correctly in the Azure serial console with the configurations that I updated.

However, despite the successful install, after reboot, I can no longer ssh into the firewall on LAN or access the HTTPS webgui on both LAN and WAN.

Any advice on why that is happening?
This is the configuration that I added:

```
  <ssh>
      <noauto>1</noauto>
      <interfaces/>
      <enabled>enabled</enabled>
      <permitrootlogin>1</permitrootlogin>
      <passwordauth>1</passwordauth>
    </ssh>
```

```
<web_gui>
      <max_procs>16</max_procs>
      <nodnsrebindcheck/>
      <nohttpreferercheck/>
</web_gui>

```
```
    <lan>
      <enable>1</enable>
      <if>mismatch0</if>
      <mtu/>
      <ipaddr>dhcp</ipaddr>
      <ipaddrv6>dhcp6</ipaddrv6>
      <subnet/>
      <gateway/>
      <blockpriv>0</blockpriv>
      <blockbogons>0</blockbogons>
      <dhcphostname/>
      <media/>
      <mediaopt/>
      <track6-interface>wan</track6-interface>
      <track6-prefix-id>0</track6-prefix-id>
    </lan>

```

**Comment by fichtner** [comment]
It depends. You can only attach to LAN if you have a WAN also. "mismatch0" doesn't look right, it should be a similar interface to what WAN is using.

**Comment by Ramzihakim** [comment]
WAN had mismatch1, so  I thought that LAN needs mismatch0 since it's the first interface and the WAN is the second interface. The DHCP configured them with the right subnets.

What is the mismatch for exactly?

**Comment by Ramzihakim** [comment]
Ah ok. I actually want it to autoconfigure with DHCP, and it did so correctly, which is why I find it very weird that I can't access the machine.

**Comment by fichtner** [comment]
it's simple really, you can't connect to the WAN DHCP address, only to the LAN address

**Comment by Ramzihakim** [comment]
That's the problem, I can't ssh to the LAN , even from the same subnet. It just times out.

**Comment by fichtner** [comment]
Can you ping LAN then? Do you connect via LAN or WAN? Are you sure you are trying to connect to the correct IP? Can you access the GUI on that same IP? It's not easy to help without these answers.

**Comment by Ramzihakim** [comment]
I actually managed to fix it by disabling the DHCP in the configuration and manually adding an allow SSH rule from the local LAN to the installation config.xml. Thanks :)

**Comment by fichtner** [comment]
Superb, happy to hear! :)
