### ISSUE TITLE
Bootstrap and DHCP

### ISSUE THREAD

**Issue by securityguy** [opnsense/update#36]
I used opnsense-bootstrap.sh to upgrade a FreeBSD box in a cloud environment, and unfortunately when it completed the LAN interface came up with a static IP of 192.168.1.1, and only the WAN used DHCP, rendering the VM inaccessible.

How can I get it to also use DHCP on the LAN interface during the upgrade process?

**Comment by fichtner** [comment]
You can push a working config to /conf/config.xml prior to bootstrap so that it comes up with the expected settings.

**Comment by securityguy** [comment]
Thank you very much!
