### ISSUE TITLE
opnsense-bootstrap.sh 19.1.tar.gz: Not Found

### ISSUE THREAD

**Issue by mhofmann-hb** [opnsense/update#45]
Bootstrapping opnsense isn´t working anymore:

sh opnsense-bootstrap.sh

Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:11:amd64/quarterly, please wait...
Verifying signature with trusted certificate pkg.freebsd.org.2013102301... done
Installing pkg-1.10.5_5...
package pkg is already installed, forced install
Extracting pkg-1.10.5_5: 100%
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Updating database digests format: 100%
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed
**fetch: https://github.com/opnsense/core/archive/stable/19.1.tar.gz: Not Found**

**Comment by fichtner** [comment]
at some point we have to switch the code to 19.1 in preparation for 19.1... https://github.com/opnsense/update/commit/35be24975

**Comment by fichtner** [comment]
This should work...

    # sh opnsense-bootstrap.sh -r 18.7

**Comment by mhofmann-hb** [comment]
thank you very much!

**Comment by fichtner** [comment]
no problem, thanks for the quick heads-up 👍 

I'll prepare stable/19.1 this week so it should all be back when 19.1-RC1 is out next week.
