### ISSUE TITLE
update: options for update server

### ISSUE THREAD

**Issue by nekoprog** [opnsense/update#50]
Hello, I'm not sure it should be here or at opnsense/core, I have a suggestion to add these options into `System: Firmware`.

There should be options for user to add other server with customs setting like:

1. url type: either pkg+http(s) or just http(s)
2. signature type: an option to select NONE
3. mirror type: an option to select NONE

I'm issuing this because I have to manually edit `/usr/local/etc/pkg/repos/OPNsense.conf` on reboot, the changes made are not persistent. And this option should be a great improvement for users who wants a bleeding-edge update from a local server.

**Comment by fichtner** [comment]
We do need to support custom mirrors eventually, but it should be somehow manageable and support multiple repositories at the same time.

What I suggest in the meantime is deactivate OPNsense.conf with a file similar to FreeBSD.conf and add your own mirror configuration to it. It should work if both are in the same file. Update can already support the signature_type != fingerprints :)

(But eventually even fingerprints should be adjustable for custom mirrors...)

**Comment by fichtner** [comment]
We allow additional trusted repos via plugins now. I think we do not add support in the GUI for drop in repos.

https://github.com/opnsense/update/issues/52
