### ISSUE TITLE
verify: support signature checks for multiple fingerprints across repositories

### ISSUE THREAD

**Issue by muratbalaban43** [opnsense/update#52]
Introducing **vendor/sunnyvalley** plugin which contains the vendor package repository information. 

Vendor-provided package repository hosts os-sensei package and related dependencies.

**Comment by fichtner** [comment]
I'm hijacking this since this is an error in pkg bootstrap base code borrowed from FreeBSD src.git.

**Comment by muratbalaban43** [comment]
@fichtner , any updates on this?

**Comment by fichtner** [comment]
@muratbalaban43 it's complicated... please test db515c8

**Comment by AdSchellevis** [comment]
@muratbalaban43 @fichtner probably needs one empty file in the revoked directory to function correctly.

```
truss opnsense-verify base-19.7.2-amd64.txz
......
stat("/usr/local/etc/pkg/fingerprints/SunnyValley/trusted/updates.sunnyvalley.org.20190702",{ mode=-rw-r--r-- ,inode=2171625,size=99,blksize=32768 }) = 0 (0x0)
openat(AT_FDCWD,"/usr/local/etc/pkg/fingerprints/SunnyValley/trusted/updates.sunnyvalley.org.20190702",O_RDONLY,00) = 6 (0x6)
mmap(0x0,99,PROT_READ,MAP_SHARED,6,0x0)		 = 4212770279424 (0x3d4dcad1000)
close(6)					 = 0 (0x0)
munmap(0x3d4dcad1000,99)			 = 0 (0x0)
getdirentries(5,0x3d4de447000,4096,{ 0x200 })	 = 0 (0x0)
close(5)					 = 0 (0x0)
open("/usr/local/etc/pkg/fingerprints/SunnyValley/revoked",O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC,033620470420) ERR#2 'No such file or directory'
opnsense-verify: write(2,"opnsense-verify: ",17)			 = 17 (0x11)
Error loading revoked certificateswrite(2,"Error loading revoked certificat"...,34) = 34 (0x22)

write(2,"\n",1)					 = 1 (0x1)
```

Then
```
mkdir /usr/local/etc/pkg/fingerprints/SunnyValley/revoked
```

```
......
lseek(3,0x0,SEEK_SET)				 = 0 (0x0)
Verifying signature with trusted certificate pkg.opnsense.org.20190702... done
write(1,"Verifying signature with trusted"...,79) = 79 (0x4f)
close(3)					 = 0 (0x0)
close(4)					 = 0 (0x0)
exit(0x0)					
process exit, rval = 0
```

**Comment by fichtner** [comment]
we should probably solve this in the plugin. I don't want to patch this too much

**Comment by AdSchellevis** [comment]
@fichtner sorry, that's what I meant as well.  how about https://github.com/opnsense/plugins/commit/195c1824cd232775e529b08922c8213aa054a53d ?

**Comment by fichtner** [comment]
looks good, but needs a revision bump for safety :)

**Comment by fichtner** [comment]
PS: so stuff works and we want it in 19.7.2 ?

**Comment by AdSchellevis** [comment]
@fichtner done, I think it's ok, if @muratbalaban43 can confirm that would be nice.

**Comment by fichtner** [comment]
ok, @muratbalaban43 a note till tomorrow would be nice then

**Comment by muratbalaban43** [comment]
@fichtner @AdSchellevis , will test today.

**Comment by muratbalaban43** [comment]
@fichtner , looks good. I was able to do a opnsense-update and that actually updated os-sensei to a new release. Thanks :)

**Comment by fichtner** [comment]
Very good, we'll be shipping all of it in 19.7.2 on Monday.

**Comment by muratbalaban43** [comment]
@fichtner thanks ! :+1:
