### ISSUE TITLE
feature request: for slow internet connections, get a download only button

### ISSUE THREAD

**Issue by hboetes** [opnsense/update#53]
One of our customers has  a very slow internet connection — Downloading the standard 290 MB ISO took an hour. I started installing the update at 3 in morning, local time, and after 6 hours the download was finished. Then the installation started, which takes about an hour and during that time the customer probably decided to restart the firewall, resulting in a broken upgrade and a bricked device. We had to get a laptop connected over that very slow connection to get console access to fix the problem.

Therefore, my feature request: please change the upgrade process in two stages:

1. download all required files.
2. wait for confirmation to start the upgrade.

So the actual upgrade can be planned and/or run at a specific time outside of production hours without having to worry about how long the download of the packages takes. Also, to ensure the upgrade doesn't actually happen during production hours.

I understand this is not an easy feature to request and barely anyone has such a slow connection these days.

**Comment by fichtner** [comment]
1. Is already true.
2. I'm not sure what you are asking: the update is scripted to be a one-step process after confirming to upgrade.

What I don't understand is this:

> Then the installation started, which takes about an hour and during that time the customer probably decided to restart the firewall, resulting in a broken upgrade and a bricked device. 

You are installing but then inferring an upgrade ran and that makes no sense... either install broke, which doesn't need to fetch or upgrade broke ini which case the install part is irrelevant. Please explain.


Cheers,
Franco

**Comment by hboetes** [comment]
>     I'm not sure what you are asking: the update is scripted to be a one-step process after confirming to upgrade.

Perhaps it's not worded entirely clearly: I want the installer to (optionally)
1) download all files
2) only after all files have downloaded get a button that says: proceed with the upgrade.

This is to ensure the time of the upgrade is done at the planned time and not 6 hours later, in case of a terribly slow internet connection.

> 
> What I don't understand is this:
> 
> > Then the installation started, which takes about an hour and during that time the customer probably decided to restart the firewall, resulting in a broken upgrade and a bricked device.

Because of the slow internet connection the download took more than 6 hours to finish and the actual upgrade — with downtime — happened during production hours.

For my glass fibre connection the download time is negligible, but not everybody has such a fast connection, there are still people who have very slow internet connections in this world.

**Comment by fichtner** [comment]
Why was the ISO mentioned and specifically "installing" ?

If this is about major upgrades there are safer methods for slow internet and slow write speed of disks/SD cards.

**Comment by hboetes** [comment]
I don’t think your comments are helpful and wonder why you are being obtuse.

**Comment by fichtner** [comment]
You have to realize that this isn't helping:

> I don’t think your comments are helpful and wonder why you are being obtuse.

**Comment by hboetes** [comment]
@AdSchellevis please take over, he’s not willing to understand.

**Comment by fichtner** [comment]
This is your second ad hominem attack. Please stop attacking me and answer my question instead to get on with the subject. There isn't much leeway and we'll simply have to close this issue if you don't want to adhere to general social rules of cooperation on this open source project.

**Comment by hboetes** [comment]
@fichtner please don’t comment on this thread any more.
