### ISSUE TITLE
Please, don't delete /usr/local/etc/pkg before verifying succesfull download of bootstrap files

### ISSUE THREAD

**Issue by terxw** [opnsense/update#57]
After unsuccessfull attemp to run bootstrap script (connection timeout) the /usr/local/etc/pkg directory was deleted before verifying successfull download.
Is this desired behaviour?

**Comment by fichtner** [comment]
Can you be more specific? I'm not aware of an issue and normally we use "set -e" to avoid going further if e.g. a download fails.

**Comment by terxw** [comment]
Thanks for reply, sorry for the delay, had too much work :(

I have problem with firmware update - localhost could not resolve hostnames, now,after adding route 0.0.0.0./0 to wan, resolve works but fetch or curl cannot connect, connection will time out, please [see my forum post ](https://forum.opnsense.org/index.php?topic=11341.msg66774#msg66774)

As an attempt to manualy upgrade i ran bootstrap script and lost my /usr/local/etc/pkg directory.

I dont know if  this directory is neccesary, just asking if another check could be added, maybe the problem was with me running script repeatedly with diferent urls... e.g. my manual edits could have caused it :)

Will manualy upgrade from usb to 19.7.5 after release.

**Comment by fichtner** [comment]
I have lost track of this, sorry. I'm not sure what's wrong, it sounds like a general setup issue leading to opnsense-bootstrap use, but to my knowledge that hasn't a lot of edge cases. A recovery opnsense-bootstrap is always left in the system as well...

**Comment by fichtner** [comment]
I'm closing this, I'm really not aware of the issue.
