### ISSUE TITLE
No signature found error when running bootstrap script

### ISSUE THREAD

**Issue by ricalo** [opnsense/update#60]
Hi,

I'm trying to install OPNsense on ZFS, but the bootstrap script fails with the mentioned error. Here are the last few lines reported by the script:

```
--
Chirp, chirp
Fetching base-20.1.7-amd64.txz: .............. done
Fetching kernel-20.1.7-amd64-11-STABLE.txz: .. failed, no signature found
root@my_host:~ #
```

I tried the bootstrap script on Hardened BSD 11.3 installed on a ZFS mirror with the following commands:
```
# pkg install ca_root_nss
# fetch https://raw.githubusercontent.com/opnsense/update/master/bootstrap/opnsense-bootstrap.sh
# sh ./opnsense-bootstrap.sh
```
I also tried on a Hardened BSD 11.3 installation without ZFS with the same result. Finally, I tried the -i flag, as follows:
```
# sh ./opnsense-bootstrap.sh -i
```
but failed with the same error.

Before trying other options, I thought I should ask if you have any pointers on how to solve this issue.

Thank you!

**Comment by AdSchellevis** [comment]
Best try using a FreeBSD 11.2 image as suggested in the readme.

> The usage is simple, starting with a FreeBSD 11.2-RELEASE image:

I don't think we support anything other than a matching base version at the moment.

**Comment by ricalo** [comment]
That worked.

It looked to me like any FreeBSD 11.x would work by looking at the script. In particular, didn't want to try 11.2 since it has reached end-of-life. But I guess it's not an issue since the bootstrapper replaces pretty much the whole system.

Thanks, @AdSchellevis! Straight answer without the snark. This is why I switched to OPNsense.
