### ISSUE TITLE
opnsense-bootstrap does not work on stock FreeBSD 12 stable or 12.1 release

### ISSUE THREAD

**Issue by cioby23** [opnsense/update#61]
Please add support to convert stock FreeBSD 12 stable/12.1 release into an OPNsense installation. Currently this is not supported.

**Comment by fichtner** [comment]
There’s a volatile/20.7 branch to use. It will become the default once 20.7 is release. We are currently in prerelease mode and users use the master branch for production systems. It’s only 8 more days... 😉
