### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by ezraholm50** [opnsense/update#7]
Hey, I've heard about this easy way to install OPNsense on a vps. Since i don't have any knowledge of FreeBSD could you tell me how to run the updater and turn a fresh FreeBSD OS into OPNsense please?

There is only a link on the support site of OPNsense and not much more to find on google about it.

Thanks for this great project!

Kind regards,

Ezra

**Comment by fichtner** [comment]
Hi Ezra,

Which VPS?  The sequence is quite simple, you start with a FreeBSD 10.3 preinstalled and simply run:

    # fetch https://raw.githubusercontent.com/opnsense/update/master/bootstrap/opnsense-bootstrap.sh
    # sh ./opnsense-bootstrap.sh

AWS is overly tricky to get right, but as long as you have a console you can change the config according to your needs and should be able to access the GUI in no time.


Cheers,
Franco

**Comment by ezraholm50** [comment]
Great, well I have a vps hosted by a company and i wanted to create a private lan and then add another vps with FreeBSD to secure it.

I had some test runs on my home lan with a VPS, took me a while to enter the GUI... still need to figure a lot of stuff out.

I will close the issue (perhaps add something like the commands i need to run to the readme? makes it easier for newbie users like me, and saves you time)

Thanks so much for the quick reply, going to test it right away!

**Comment by fichtner** [comment]
I've put the instructions on the front page, thanks for the idea! :)

https://github.com/opnsense/update#opnsense-bootstrap

**Comment by ezraholm50** [comment]
@fichtner I hope you are doing well! Quick question, how to do this on ARM6 same as above or do I run the number 8 version of bootstrap?

**Comment by fichtner** [comment]
@ezraholm50 sorry, took me a bit to get back to this: what do you mean exactly? I'm not fully understanding the question?

**Comment by jasonkinsella** [comment]
Hi, can I use this process in AWS? I've tried with a FreeBSD 11.2 and the bootstrap finished successfully. After reboot the VM was not accessible. Is there any additional steps required for AWS?

**Comment by fichtner** [comment]
Hi @jasonkinsella,

It's possible, but AWS requires to place a correct /conf/config.xml in the system prior to bootstrap so it comes back as expected (network settings, interface names).

Or you can take a look at https://docs.opnsense.org/manual/how-tos/installaws.html


Cheers,
Franco
