### ISSUE TITLE
21.1 Not found

### ISSUE THREAD

**Issue by daniele338** [opnsense/update#72]
## Issue 

I downloaded and executed the file opnsense-bootstrap.sh.in on a machine with FreeBSD 12.2.2 but it can't install opnsense, I executed the command 

`sh ./opnsense-bootstrap.sh.in -r 21.1
`
that returned the error 

`https://github.com/opnsense/core/archive/stable/21.1.tar.gz Not found
`
At the moment I think that I have somehow fixed this issue, but I'd like to understand if I did some mistake in executing the command.

## Workaround 

Right now I bypassed this issue by making the following changes inside the file opnsense-bootstrap.sh.in:

```
URL="https://github.com/opnsense/core/archive"  --> URL="https://github.com/opnsense/core/archive/refs/tags/"
SUBFILE="stable/${RELEASE}" --> SUBFILE="${RELEASE}"
```
After the changes mentioned above it returned another error

`make chdir /tmp/opnsense-bootstrap/core-stable-21.1/ Not found 
`
And to bypass this error I made this change 

`SUBDIR="stable-${RELEASE}" --> SUBDIR="${RELEASE}"  
`

**Comment by fichtner** [comment]
> https://github.com/opnsense/core/archive/stable/21.1.tar.gz Not found

It works from here. Make sure you don't have any proxies and that GitHub is not playing tricks on you.


Cheers,
Franco

**Comment by daniele338** [comment]
Right now it works. I think it was an issue with github.
Thank you very much and sorry for disturbing.

**Comment by fichtner** [comment]
@daniele338 no problem, thanks for reporting! :)
