### ISSUE TITLE
freebsd 14?

### ISSUE THREAD

**Issue by gdoteof** [opnsense/update#84]
i was able to get freebsd 14 to up on a nanopi 5rs (though only after realizing it was crashing if a usb keyboard was plugged in at boot!); the bootstrap script here had several checks blocking the execution when i tried to turn this into an opnsense install.  i tried simply disabling all the checks as they came up, and unsurprisingly i didn't get it it up.

i saw that freebsd 14 just came out.  i am curious the timeline/effort of this script being updated to support freebsd 14; and/or if its even feasible to get past this point without opnsense updating packages

this is where it got after disabling a few checks in the shell script
```sh

The operation will free 33 MiB.
[1/2] Deinstalling pkg-1.19.1_1...
[1/2] Deleting files for pkg-1.19.1_1: 100%
[2/2] Deinstalling ca_root_nss-3.89.1...
[2/2] Deleting files for ca_root_nss-3.89.1:  11%
ca_root_nss-3.89.1: missing file /usr/local/etc/ssl/cert.pem
[2/2] Deleting files for ca_root_nss-3.89.1:  33%
ca_root_nss-3.89.1: missing file /usr/local/openssl/cert.pem
[2/2] Deleting files for ca_root_nss-3.89.1: 100%
make: "/tmp/opnsense-bootstrap/core-stable-23.1/Makefile" line 39: warning: Cannot build without CORE_PHP set
make: "/tmp/opnsense-bootstrap/core-stable-23.1/Makefile" line 39: warning: Cannot build without CORE_PYTHON set
make: "/tmp/opnsense-bootstrap/core-stable-23.1/Makefile" line 39: warning: Cannot build without CORE_PHP set
make: "/tmp/opnsense-bootstrap/core-stable-23.1/Makefile" line 39: warning: Cannot build without CORE_PYTHON set
Bootstrapping pkg from http://pkg.freebsd.org/FreeBSD:14:aarch64/latest, please wait...
Installing pkg-1.19.1_1...
Extracting pkg-1.19.1_1: 100%
Updating OPNsense repository catalogue...
pkg: https://pkg.opnsense.org/FreeBSD:14:aarch64/23.1/latest/meta.txz: Not Found
repository OPNsense has no meta file, using default settings
pkg: https://pkg.opnsense.org/FreeBSD:14:aarch64/23.1/latest/packagesite.pkg: Not Found
pkg: https://pkg.opnsense.org/FreeBSD:14:aarch64/23.1/latest/packagesite.txz: Not Found
Unable to update repository OPNsense
Error updating repositories!
```

**Comment by fichtner** [comment]
FreeBSD 14.0 is not even out for about two months (if the schedule holds) https://www.freebsd.org/releases/14.0R/schedule/

We won't be using 14.0 anyway so 14.1 puts us into 2024 so ideally 24.7 will support 14.1 but not sooner.
