### ISSUE TITLE
update: pkg+ remnants prevent changing the mirror location

### ISSUE THREAD

**Issue by computeralex92** [opnsense/update#87]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

The overview page of "Firmware" is not showing correctly the used mirror:

![SCR-20231025-mmxu](https://github.com/opnsense/core/assets/6564612/1bafa277-9bcd-4be4-bfab-f449abb65f99)

The mirror is set correctly; a restart or change in the settings do not reflect on the overview page: 
![SCR-20231025-mnex](https://github.com/opnsense/core/assets/6564612/6a02a70c-a945-4df4-a5be-82d0bbf4e740)

**To Reproduce**

1. Go to 'System/Firmware'
2. Click on 'Settings'
3. Change to a different mirror 
4. Click on Save
5. Click on Status
6. Check for updates

**Expected behavior**

The used mirror is shown in the status page.

**Describe alternatives you considered**

I tried to switch to a different mirror and restarted the opnsense, but this status page is still showing the default mirror.

**Screenshots**

See above

**Relevant log files**

**Additional context**

**Environment**

Software version used and hardware type if relevant, e.g.:

OPNsense 23.7.7-amd64
FreeBSD 13.2-RELEASE-p3
OpenSSL 1.1.1w  11 Sep 2023
Intel(R) Core(TM) i3-5005U

**Comment by fichtner** [comment]
Hotfixed this now. Thanks for the report.
