### ISSUE TITLE
gettext-runtime-0.22.5: already unlocked when starting the ./opnsense-bootstrap.sh.in

### ISSUE THREAD

**Issue by olif0x** [opnsense/update#97]
So i have a VPS with FreeBSD 14.0-RELEASE (GENERIC) #0 releng/14.0-n265380-f9716eee8ab4 installed and wanted to use the skript to create an OPNsense Installation out of it.

But after downloading the file i always get this "gettext-runtime-0.22.5: already unlocked" message and cannot proceed further or atleast nothing is happening.

unfortunately i can't find anything on the web regarding this message and this opnsense skript file and i don't know how these [search-entries](https://www.startpage.com/do/dsearch?q=gettext-runtime-0.22.5%3A+already+unlocked&cat=web&language=english) would help me, therefore i hope you can tell my why this script can run or rather how i could handle this error.

**Comment by fichtner** [comment]
See https://github.com/opnsense/update/issues/93#issuecomment-2242714677
